name: Sync Fork

on:
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  sync:
    if: github.repository_owner == 'pmkol' || github.repository_owner == 'apadpro'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'master'
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
      - name: Merge upstream changes
        run: |
          git remote add upstream https://github.com/destan19/OpenAppFilter.git
          git fetch upstream
          git merge upstream/master --allow-unrelated-histories --no-edit || exit 1
      - name: Push changes
        run: git push
